### ISSUE TITLE
Tidy up branches

### ISSUE THREAD

**Issue by ChloeRN** [GhanSaridnirun/Green-Peafowl-Population_Project__GS#10]
This repository has 7 branches at present, most of which seem obsolete now. 
I have merged the two "most recent" side branches into the master. 

@GhanSaridnirun please check which of the branches are still necessary, and delete the others. 
I suggest we continue our work from here on with making new branches off the main now.

**Comment by DrMattG** [comment]
Cleaned up branches and merged all changes in to Main
